# Generated by Django 6.0.2 on 2026-02-04 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlagiarismReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_percentage', models.FloatField()),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('base_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_reports', to='detector.uploadeddocument')),
                ('compared_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compared_reports', to='detector.uploadeddocument')),
            ],
        ),
    ]
