# Generated by Django 6.0.2 on 2026-02-21 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0003_emailotp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plagiarismreport',
            options={'ordering': ['-checked_at']},
        ),
        migrations.AddField(
            model_name='plagiarismreport',
            name='severity',
            field=models.CharField(default='Low', max_length=20),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
