# Generated by Django 6.0.2 on 2026-02-26 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0005_comparisonhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlagiarismHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.CharField(choices=[('essay', 'Essay Plagiarism'), ('code', 'Code Plagiarism')], max_length=10)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.FloatField()),
                ('risk_level', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
