# Generated by Django 6.0.2 on 2026-02-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0006_plagiarismhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('result_type', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('score', models.FloatField(default=0)),
                ('risk_level', models.CharField(default='Low', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
