# Generated by Django 6.0.2 on 2026-03-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0007_userhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('category', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
